"""empty message

Revision ID: 77e99905ae73
Revises: 
Create Date: 2026-05-23 14:21:43.702984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77e99905ae73'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LeaveApplication',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employeeId', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('Sick', 'Casual', 'Annual', name='leavetype'), nullable=False),
    sa.Column('startDate', sa.Date(), nullable=False),
    sa.Column('endDate', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'Approved', 'Rejected', name='leavestatus'), server_default=sa.text("'Pending'"), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['employeeId'], ['Employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Payslip',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employeeId', sa.Integer(), nullable=False),
    sa.Column('month', sa.INTEGER(), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=False),
    sa.Column('basicSalary', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('allowances', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('deductions', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('netSalary', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['employeeId'], ['Employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('createdAt', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
        batch_op.add_column(sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Attendance', schema=None) as batch_op:
        batch_op.drop_column('updatedAt')
        batch_op.drop_column('createdAt')

    op.drop_table('Payslip')
    op.drop_table('LeaveApplication')
    # ### end Alembic commands ###
